#pragma once
#include <dcd/vm/opcodes_def.hpp>
#include <dcd/vm/variant.hpp>

#include <map>

namespace dcd { namespace vm {
   enum opcodes {
      DCD_VM_CONTROL_FLOW_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_BR_TABLE_OP(DCD_VM_CREATE_ENUM)
      DCD_VM_RETURN_OP(DCD_VM_CREATE_ENUM)
      DCD_VM_CALL_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_CALL_IMM_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_PARAMETRIC_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_VARIABLE_ACCESS_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_MEMORY_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_I32_CONSTANT_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_I64_CONSTANT_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_F32_CONSTANT_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_F64_CONSTANT_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_COMPARISON_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_NUMERIC_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_CONVERSION_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_EXIT_OP(DCD_VM_CREATE_ENUM)
      DCD_VM_EMPTY_OPS(DCD_VM_CREATE_ENUM)
      DCD_VM_ERROR_OPS(DCD_VM_CREATE_ENUM)
   };

   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         DCD_VM_CONTROL_FLOW_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_BR_TABLE_OP(DCD_VM_CREATE_MAP)
         DCD_VM_RETURN_OP(DCD_VM_CREATE_MAP)
         DCD_VM_CALL_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_CALL_IMM_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_PARAMETRIC_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_VARIABLE_ACCESS_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_MEMORY_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_I32_CONSTANT_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_I64_CONSTANT_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_F32_CONSTANT_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_F64_CONSTANT_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_COMPARISON_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_NUMERIC_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_CONVERSION_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_EXIT_OP(DCD_VM_CREATE_MAP)
         DCD_VM_EMPTY_OPS(DCD_VM_CREATE_MAP)
         DCD_VM_ERROR_OPS(DCD_VM_CREATE_MAP)
      };
   };

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   DCD_VM_CONTROL_FLOW_OPS(DCD_VM_CREATE_CONTROL_FLOW_TYPES)
   DCD_VM_BR_TABLE_OP(DCD_VM_CREATE_BR_TABLE_TYPE)
   DCD_VM_RETURN_OP(DCD_VM_CREATE_CONTROL_FLOW_TYPES)
   DCD_VM_CALL_OPS(DCD_VM_CREATE_CALL_TYPES)
   DCD_VM_CALL_IMM_OPS(DCD_VM_CREATE_CALL_IMM_TYPES)
   DCD_VM_PARAMETRIC_OPS(DCD_VM_CREATE_TYPES)
   DCD_VM_VARIABLE_ACCESS_OPS(DCD_VM_CREATE_VARIABLE_ACCESS_TYPES)
   DCD_VM_MEMORY_OPS(DCD_VM_CREATE_MEMORY_TYPES)
   DCD_VM_I32_CONSTANT_OPS(DCD_VM_CREATE_I32_CONSTANT_TYPE)
   DCD_VM_I64_CONSTANT_OPS(DCD_VM_CREATE_I64_CONSTANT_TYPE)
   DCD_VM_F32_CONSTANT_OPS(DCD_VM_CREATE_F32_CONSTANT_TYPE)
   DCD_VM_F64_CONSTANT_OPS(DCD_VM_CREATE_F64_CONSTANT_TYPE)
   DCD_VM_COMPARISON_OPS(DCD_VM_CREATE_TYPES)
   DCD_VM_NUMERIC_OPS(DCD_VM_CREATE_TYPES)
   DCD_VM_CONVERSION_OPS(DCD_VM_CREATE_TYPES)
   DCD_VM_EXIT_OP(DCD_VM_CREATE_EXIT_TYPE)
   DCD_VM_EMPTY_OPS(DCD_VM_CREATE_TYPES)
   DCD_VM_ERROR_OPS(DCD_VM_CREATE_TYPES)

   using opcode = variant<
      DCD_VM_CONTROL_FLOW_OPS(DCD_VM_IDENTITY)
      DCD_VM_BR_TABLE_OP(DCD_VM_IDENTITY)
      DCD_VM_RETURN_OP(DCD_VM_IDENTITY)
      DCD_VM_CALL_OPS(DCD_VM_IDENTITY)
      DCD_VM_CALL_IMM_OPS(DCD_VM_IDENTITY)
      DCD_VM_PARAMETRIC_OPS(DCD_VM_IDENTITY)
      DCD_VM_VARIABLE_ACCESS_OPS(DCD_VM_IDENTITY)
      DCD_VM_MEMORY_OPS(DCD_VM_IDENTITY)
      DCD_VM_I32_CONSTANT_OPS(DCD_VM_IDENTITY)
      DCD_VM_I64_CONSTANT_OPS(DCD_VM_IDENTITY)
      DCD_VM_F32_CONSTANT_OPS(DCD_VM_IDENTITY)
      DCD_VM_F64_CONSTANT_OPS(DCD_VM_IDENTITY)
      DCD_VM_COMPARISON_OPS(DCD_VM_IDENTITY)
      DCD_VM_NUMERIC_OPS(DCD_VM_IDENTITY)
      DCD_VM_CONVERSION_OPS(DCD_VM_IDENTITY)
      DCD_VM_EXIT_OP(DCD_VM_IDENTITY)
      DCD_VM_EMPTY_OPS(DCD_VM_IDENTITY)
      DCD_VM_ERROR_OPS(DCD_VM_IDENTITY_END)
      >;
}} // namespace dcd::vm
