version: "3.7"
services:
  node:
    container_name: usernode
    extends:
      file: node.yml
      service: node
    ports:
      - "8888:8888"
      - "8022:8022"
      - "7000:7000"
      - "8899:8899"
      - "9022:9022"
      - "9012:9012"
    network_mode: host
    volumes:
      - ./config:/node/config
      - ./log:/node/log
      - ./blockchain:/node/blockchain
