#!/bin/bash
curdir=$(dirname $(realpath "0"))
cd $curdir
sudo rm -rf $curdir/node0/blockchain/
sudo rm -rf $curdir/node0/log/
sudo rm -rf $curdir/node0/dcd_wall/
sudo rm -rf $curdir/node0/workblockchain/
sudo rm -rf $curdir/node0/worklog/
sudo rm -rf $curdir/node0/config/config_created.lock
sudo rm -rf $curdir/node0/config/genesis/desabled.lock

sudo rm -rf $curdir/accountnum11/blockchain/
sudo rm -rf $curdir/accountnum11/config/genesis/ipaddr
sudo rm -rf $curdir/accountnum11/log/
sudo rm -rf $curdir/accountnum12/blockchain/
sudo rm -rf $curdir/accountnum12/config/genesis/ipaddr
sudo rm -rf $curdir/accountnum12/log/
sudo rm -rf $curdir/accountnum13/blockchain/
sudo rm -rf $curdir/accountnum13/config/genesis/ipaddr
sudo rm -rf $curdir/accountnum13/log/
sudo rm -rf $curdir/accountnum14/blockchain/
sudo rm -rf $curdir/accountnum14/config/genesis/ipaddr
sudo rm -rf $curdir/accountnum14/log/
sudo rm -rf $curdir/accountnum15/blockchain/
sudo rm -rf $curdir/accountnum15/config/genesis/ipaddr
sudo rm -rf $curdir/accountnum15/log/

sudo rm -rf $curdir/accountnum11/config/genesis/genesis_start.sh
sudo rm -rf $curdir/accountnum11/config/genesis/hard_replay.sh
sudo rm -rf $curdir/accountnum11/config/genesis/start.sh
sudo rm -rf $curdir/accountnum12/config/genesis/genesis_start.sh
sudo rm -rf $curdir/accountnum12/config/genesis/hard_replay.sh
sudo rm -rf $curdir/accountnum12/config/genesis/start.sh
sudo rm -rf $curdir/accountnum13/config/genesis/genesis_start.sh
sudo rm -rf $curdir/accountnum13/config/genesis/hard_replay.sh
sudo rm -rf $curdir/accountnum13/config/genesis/start.sh
sudo rm -rf $curdir/accountnum14/config/genesis/genesis_start.sh
sudo rm -rf $curdir/accountnum14/config/genesis/hard_replay.sh
sudo rm -rf $curdir/accountnum14/config/genesis/start.sh
sudo rm -rf $curdir/accountnum15/config/genesis/genesis_start.sh
sudo rm -rf $curdir/accountnum15/config/genesis/hard_replay.sh
sudo rm -rf $curdir/accountnum15/config/genesis/start.sh
sudo rm -rf $curdir/node0/config/accountnum11/genesis_start.sh
sudo rm -rf $curdir/node0/config/accountnum11/hard_replay.sh
sudo rm -rf $curdir/node0/config/accountnum11/start.sh
sudo rm -rf $curdir/node0/config/accountnum12/genesis_start.sh
sudo rm -rf $curdir/node0/config/accountnum12/hard_replay.sh
sudo rm -rf $curdir/node0/config/accountnum12/start.sh
sudo rm -rf $curdir/node0/config/accountnum13/genesis_start.sh
sudo rm -rf $curdir/node0/config/accountnum13/hard_replay.sh
sudo rm -rf $curdir/node0/config/accountnum13/start.sh
sudo rm -rf $curdir/node0/config/accountnum14/genesis_start.sh
sudo rm -rf $curdir/node0/config/accountnum14/hard_replay.sh
sudo rm -rf $curdir/node0/config/accountnum14/start.sh
sudo rm -rf $curdir/node0/config/accountnum15/genesis_start.sh
sudo rm -rf $curdir/node0/config/accountnum15/hard_replay.sh
sudo rm -rf $curdir/node0/config/accountnum15/start.sh
sudo rm -rf $curdir/node0/config/work/genesis_start.sh
sudo rm -rf $curdir/node0/config/work/hard_replay.sh
sudo rm -rf $curdir/node0/config/work/start.sh