version: "3.7"
services:
  node:    
    image: dcd_prot_img
    tty: true
    command: bash -c "/node/config/run.sh; touch /node/log/dcdnode.log; tail -f /node/log/dcdnode.log"
    expose:
      - "9022"
